# Generated by Django 5.0.2 on 2024-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='product_photos/'),
        ),
    ]
